
#0 будет динамически устанавливать свободный порт во время старта
server:
  port: 0

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/order-service
    username: postgres
    password: root

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
